name: enchanted_event_hall
description: Enchanted Event Hall Mobile Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0

  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.2

  # Local storage / caching
  shared_preferences: ^2.2.2

  # UI enhancement (SVG support)
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login_and_register_background/
    - assets/logo/
    - assets/guest_home/
    - assets/halls/



